# Generated by Django 2.2.6 on 2020-11-29 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201122_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',), 'verbose_name': 'пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
